// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{platform}/alerts": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Show Alertsdata"
                ],
                "summary": "Show current Alerts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "lang select",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/parser.Alerts"
                        }
                    }
                }
            }
        },
        "/{platform}/darvo": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Show DarvoDeals"
                ],
                "summary": "Show active  Darvo Deals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "lang select",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/parser.DarvoDeals"
                        }
                    }
                }
            }
        },
        "/{platform}/news": {
            "get": {
                "description": "get string by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Show Newsdata"
                ],
                "summary": "Show current News",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Platform",
                        "name": "platform",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "lang select",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/parser.News"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "parser.Alerts": {
            "type": "object",
            "properties": {
                "ends": {
                    "type": "string"
                },
                "enemyWaves": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "maxEnemyLevel": {
                    "type": "integer"
                },
                "minEnemyLevel": {
                    "type": "integer"
                },
                "missionFaction": {
                    "type": "string"
                },
                "missionLocation": {
                    "type": "string"
                },
                "missionType": {
                    "type": "string"
                },
                "rewardCredits": {
                    "type": "integer"
                },
                "rewardItem": {
                    "type": "string"
                },
                "rewardItemMany": {
                    "type": "string"
                },
                "rewardItemManyCount": {
                    "type": "integer"
                },
                "started": {
                    "type": "string"
                }
            }
        },
        "parser.DarvoDeals": {
            "type": "object",
            "properties": {
                "dealPrice": {
                    "type": "integer"
                },
                "discountPercent": {
                    "type": "integer"
                },
                "ends": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "item": {
                    "type": "string"
                },
                "itemtest": {
                    "type": "string"
                },
                "price": {
                    "type": "integer"
                },
                "sold": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                }
            }
        },
        "parser.News": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "api.tenno.dev",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tenno.dev  APIs",
	Description:      "Tenno.dev  APIs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
